apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Oracle Storage
  description: Oracle Storage Plugin for Reekoh IoT Platform.
  documentation: README.md
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Storage
  price: 0
  tags:
    - storage
    - oracle
  config:
    connection:
      label: Connection String
      type: String
      maxLength: 1000
      required: true
      help: "Connection String for the Oracle Server format - [host]:[port]/[sid or service name]."
    user:
      label: User
      type: String
      maxLength: 1000
      required: true
      help: "Username for Oracle Server Authentication."
    password:
      label: Password
      type: Password
      maxLength: 1000
      required: true
      help: "Password for Oracle Server Authentication."
    schema:
      label: User Schema
      type: String
      maxLength: 1000
      required: false
      help: "(Optional) User Schema in the Oracle Database where data will be written into."
    table:
      label: Table
      type: String
      maxLength: 1000
      required: true
      help: "Table name in the Oracle Database where data will be written into."
    fieldMapping:
      label: Field Mapping
      type: String
      maxLength: 1000
      required: true
      help: "List of the Table Fields/Columns. Input for this field is in JSON format {\"(field_name)\" : {\"source_field\" : \"value\", \"data_type\": \"value\", \"format\": \"value\"}}. field_name will be the name of the column in the Oracle Table, source_field (required) value will be the name of the field in the JSON Data passed to the plugin, data_type (optional) there are 6 available data types that will convert data to it's proper type before saving we have String, Integer, Float, Boolean, Timestamp and Date, format is only available for Timestamp and Date data_type allowing users to specify the format of the device date/time data value. Kindly refer to the MomentJS docs for more details (http://momentjs.com/docs/#/parsing/string-format/)."

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    image: path/to/docker/image # ??